### ISSUE TITLE
Installation prestashop 1.6.1

### ISSUE THREAD

**Issue by franck85** [DonatasL/PrestaShop-ElasticSearch#1]
Bonjour,

j'ai voulu faire un essais de votre module mais l'installation est impossible.

J'ai charger le module via prestashop et le module n'est pas visible par la suite.

l'installation est elle possible avec prestashop 1.6.1?

Cordialement,
Franck

**Comment by DonatasL** [comment]
Hello Franck,
Sorry, I will not be able to answer you in French, but I will answer in English.

Currently we are working on the new version of this module. It will be compatible with PS 1.6.1 and also will be much faster - we are doing some optimization.

We think that the new release will be available in couple of weeks.

If you have any questions do not hesitate to ask.

**Comment by franck85** [comment]
Thank you for your response.
I am curious to know the behavior of your search module with my site .

I use more than 1500000 in the registration tag and it is very heavy for the search engine "native" prestashop .

I have a connection module sphinxsearch but this seems complicated for the implementation of it .

Regards,
Franck

- >> translation by google .

**Comment by DonatasL** [comment]
Hi,
our experience shows that "Elastic search" is very friendly for developers so easy to implement. It also scales nicely and easy.

Elastic search will handle 1500000 products - it's just a mater of server configuration and hardware resources. Probably testing will be needed in order to understand what is the optimal configuration for 1500000 products but it's doable and performance should be really fast.

Hope my answer has answered your question :)

**Comment by DonatasL** [comment]
Hi,
elastic search will be able to handle this amount of products and product_tags without any issue :) These numbers looks quite small if speaking honestly.

**Comment by franck85** [comment]
La recherche ne devrais alors pas être trop lente :-)
Avez vous un site en production qui utilise votre module ?

Franck

**Comment by DonatasL** [comment]
Hi,
one of our clients is using this module (a bit more modified version). This website should go live next week if everything will go according the plan, then I can send you the link for testing if needed.

**Comment by franck85** [comment]
yes I am willing to give it a module overview

**Comment by DonatasL** [comment]
OK, lets wait for the next week then.

**Comment by DonatasL** [comment]
Hi Franck,
here is the example of elastic search integration with PrestaShop:
http://www.deelat.com/fasteners/flange-screws/hex-flange/
http://www.deelat.com/vehiclefleet-maintenance/drones/

Total about 10 000 products. Not too many in one category but anyway you can see how fast the search is made - it's even hard to notice when products has changed.

**Comment by franck85** [comment]
Hello,

yes actually it's very fast .

**Comment by teototaro** [comment]
Hi, the version online right now is compatible with PrestaShop 1.6.1.1?
If yes how can I set up the module?
Thanks

**Comment by DonatasL** [comment]
Hello Matteo Totaro,
I would recommend to wait few weeks - we are very close with our new release. Yes it will be compatible with PrestaShop 1.6.1.1.
Installation and configuration will be very easy - few lines of parameters.

**Comment by teototaro** [comment]
Ok, thank you, have you a mailing list to subscribe to receive the release notification?

**Comment by DonatasL** [comment]
Hello Matteo Totaro,
yes you can subscribe here: http://bradsearch.com/

**Comment by SiddiqueAhmad** [comment]
we are waiting, and subscribed to list as well, how long it will take ??

i am uploading the zip file but it is not detecting as module

**Comment by devdesco-ceo** [comment]
Connection to elastic search service is unavailable

**Comment by DonatasL** [comment]
@devdesco-ceo have you configured  your elastic search service and port is not blocked by any firewall?

**Comment by devdesco-ceo** [comment]
I have ElasticSearch running on separate server in a subnet, and can successfully connect with Kibana, or just telnet the 9200 port on that machine from any other machine in a subnet, as well from my frontend server. I just installed the plugin under Prestashop. Do I need to do any other WooDoo dancing besides installing the plugin, and punching in IP:PORT for my ElasticSearch server?

**Comment by DonatasL** [comment]
@devdesco-ceo  what response do you get when you try to reach in browser this URL: http://ip_address_of_elastic_service:9200 (or other port you use)?

Are you using version from master branch (it was updated recently)?

No "woodoo" is needed :) if my comments does not help maybe we could arrange team-viewer session?

**Comment by devdesco-ceo** [comment]
curl -i -X GET http://app3:9200/_cluster/health?pretty=true
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 466

{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 6,
  "active_shards" : 6,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 6,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}

**Comment by devdesco-ceo** [comment]
![image 32](https://cloud.githubusercontent.com/assets/8983883/11150447/b420480c-89ed-11e5-9cb4-c721f5a7616d.png)

**Comment by devdesco-ceo** [comment]
Can the connection issue be due to ElasticSearch being at version 2.0.0 instead of 1.x.x?

**Comment by DonatasL** [comment]
Hello @devdesco-ceo , yes probably this is the issue. We are going to test it / make changes during next week.

**Comment by devdesco-ceo** [comment]
Confirming that it works fine on ES 1.7, but not on ES2.0

**Comment by rokaszygmantas** [comment]
Made some compatibility changes (for ES 2.0), so it should work now :)
