### ISSUE TITLE
Wordking on MacOSX ?

### ISSUE THREAD

**Issue by monpoulet** [DonatasL/PrestaShop-ElasticSearch#2]
Hi guy,

I have installed ElasticSerach on MacOSX Yosemite and your module on PS 1.0.014 and 1.6.1.1, and I have an issue when setting the server address in the settings page of the Brad Module:
[PrestaShop] Fatal error in module file :/Library/WebServer/Documents/16014/modules/elasticsearch/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:
Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/Library/WebServer/Documents/16014/modules/elasticsearch/logs/ElasticSearchService.html" could not be opened: failed to open stream: Permission denied' in /Library/WebServer/Documents/16014/modules/elasticsearch/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84 Stack trace: #0 /Library/WebServer/Documents/16014/modules/elasticsearch/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /Library/WebServer/Documents/16014/modules/elasticsearch/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /Library/WebServer/Documents/16014/modules/elasticsearch/vendor/monolog/monolog/src/Monolog/Logger.php(329): Monolog\Logger->addRecord(400, 'Search failed', Array) #3 /Library/WebServer/Documents/16014/modules/elasticsearch/classes/SearchService.php(150): Monolog\Logger->addError('Search failed', Arr

Do you have an idea how to fix that ?

Marc

**Comment by DonatasL** [comment]
Hi Marc,
as I see the module tries to write error message to module logs file: /Library/WebServer/Documents/16014/modules/elasticsearch/logs/ElasticSearchService.html

Probably directory one of these is not writeable:
- directory: Library/WebServer/Documents/16014/modules/elasticsearch/logs/
- or file Library/WebServer/Documents/16014/modules/elasticsearch/logs/ElasticSearchService.html

Check permissions if your web server can write to this directory or file. Usually this file is created automatically, but you should check this.

I want also to emphasize that current module version is quite unstable and we are making many changes. Our plan is to provide the new release in 1-2 months which will be much more stable.

If you have any questions please feel free to ask.
Thanks!

**Comment by monpoulet** [comment]
Hello Donatas,

You cal close the issue, Composer was not installed... Now it's work like a
charm.
Please let me know when the new version will be available.

Marc

2015-08-31 14:03 GMT+02:00 DonatasL <notifications@github.com>:

**Comment by DonatasL** [comment]
Hi Marc,
glad you have resolved your issue!
