### ISSUE TITLE
Can not index products on PS 1.6.0.9

### ISSUE THREAD

**Issue by j99** [DonatasL/PrestaShop-ElasticSearch#4]
My elasticsearch is running, I configured IP & port correctly but when I index the products, nothing is indexed.

Log file states:
Message: 	
Unable to index all products. Message: 
Time: 	
2015-10-13 09:34:49
Channel: 	
ElasticSearchService

and then if I try to search something, I get:
Message: 	
Search failed
Time: 	
2015-10-13 09:36:29
Channel: 	
ElasticSearchService
Context: 	
Message: 	
{"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed]","status":503}
index: 	
iogfho3j_1
params: 	
{
    "index": "iogfho3j_1",
    "body": {
        "query": {
            "match_all": []
        }
    },
    "type": "products",
    "search_type": "count"
}

I guess something is wrong with configuration, I am using PHP 5.6 and elasticsearch 1.7.2
The only thing I did is installed module according to the instructions (upload & install) and configured right IP address and port of elasticsearch server.

**Comment by DonatasL** [comment]
Hello!
Are you using master or dev branch for installation?

**Comment by j99** [comment]
I am using master

**Comment by j99** [comment]
Just tried using dev and when I index all products I get immediately " Products indexed successfully "

But log now has a bit more information:

Unable to index all products. Error code: 503. Message: Server error response
[status code] 503
[reason phrase] Service Unavailable
[url] http://127.0.0.1:9200/iogfho3j_1/products/1

**Comment by DonatasL** [comment]
According to the error message it seems that ElasticSearch service is not running or it's not accessible (e.g. blocked by firewall).
What do you see when you go to this link:  http://127.0.0.1:9200 ?

Please master branch, as dev branch is not stable.

**Comment by j99** [comment]
When I go to this link I get:

{
  "status" : 200,
  "name" : "Spider-Man",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by rokaszygmantas** [comment]
Hi, j99!

We have released a relatively big update to the module on 2015 Dec 14, maybe this update would fix your issue, please give it a try :)
