### ISSUE TITLE
Install times out with 504 Error (nginx)

### ISSUE THREAD

**Issue by techjp** [DonatasL/PrestaShop-ElasticSearch#8]
I discovered BRAD a couple of days ago and have been trying to get it to work since.

BRAD installs on my Bitnami PrestaShop VM (1.6.1.4). However for the live site I will be using a Cloudways.com/Vultr VPS, and Cloudways uses nginx instead of Apache. I have Elasticsearch installed and the PHP API installed, but for the life of me I can't get BRAD to install. After uploading the files (tried auto and manual) I start the install. The install stalls forever and eventually times out with a 504 Gateway Timeout error.

I set up a fresh Prestashop installation to test with so I am certain there is nothing I have previously mucked up with Prestashop to make this happen.

I would be most grateful for any help with this, and would be happy to give you credentials to test with the VPS if that would be helpful. (They do offer a 30 day free trial currently though so that may be an option for testing too.)

Thank you very much for any time and assistance, I'd really love to get this working!

Ian

**Comment by simonasinvertus** [comment]
Thank you for showing interest in Brad module.
We are currently overwhelmed with work on other projects but we could arrange paid support.
If you are interested please write a message to help@invertus.eu

**Comment by techjp** [comment]
Thank you for your reply.

For now I'll work with the Bitnami images rather than trying to get BRAD to work on nginx.

Do you think you will update BRAD to work with future versions of PrestaShop, such as the upcoming 1.7?

**Comment by simonasinvertus** [comment]
Yes, of course. 

We made Brad for some of our clients, so as soon as our clients will want to upgrade or we will have free time/less intense period (which ever happens first) we will make Brad compatible with upcoming PrestaShop versions.

**Comment by techjp** [comment]
Thank you!
