### ISSUE TITLE
Product indexation hangs up the whole site in PS 1.5.6.2

### ISSUE THREAD

**Issue by IndreIndre** [DonatasL/PrestaShop-ElasticSearch#9]
Hi,

Everything seems Ok and running, but when I try to reindex missing products, it hangs up the whole MySql server. 
It is the PS 1.5.6.2. 
Can you help us to find the reason?

**Comment by simonasinvertus** [comment]
Thank you for showing interest in Brad.

Brad was developed for PS1.6 version and currently is not adapted to earlier PrestaShop versions.
